obj-$(CONFIG_MACH_APQ8064_L05E) += board-L05E.o \
	board-L05E-camera.o \
	board-L05E-display.o \
	board-L05E-gpiomux.o \
	board-L05E-gpu.o \
	board-L05E-pmic.o \
	board-L05E-input.o \
	board-L05E-regulator.o \
	board-L05E-misc.o \
	board-L05E-storage.o \
	board-L05E-rfkill.o \
	board-L05E-sound.o
