obj-$(CONFIG_MACH_APQ8064_GVDCM) += board-gv.o \
	board-gv-camera.o \
	board-gv-display.o \
	board-gv-gpiomux.o \
	board-gv-gpu.o \
	board-gv-pmic.o \
	board-gv-regulator.o \
	board-gv-misc.o \
	board-gv-sound.o \
	board-gv-storage.o \
	board-gv-nfc.o \
	board-gv-rfkill.o

obj-$(CONFIG_MACH_APQ8064_GVKDDI) += board-gv.o \
	board-gv-camera.o \
	board-gv-display.o \
	board-gv-gpiomux.o \
	board-gv-gpu.o \
	board-gv-pmic.o \
	board-gv-regulator.o \
	board-gv-misc.o \
	board-gv-sound.o \
	board-gv-storage.o \
	board-gv-nfc.o
	
