obj-$(CONFIG_MACH_APQ8064_GVKT) += board-gk.o \
	board-gk-camera.o \
	board-gk-display.o \
	board-gk-gpiomux.o \
	board-gk-gpu.o \
	board-gk-pmic.o \
	board-gk-regulator.o \
	board-gk-misc.o \
	board-gk-sound.o \
	board-gk-storage.o \
	board-gk-nfc.o \
	board-gk-rfkill.o
