#
# Makefile for the broadcast(ISDB-T) RF/BB core.
#
#obj-$(CONFIG_LGE_BROADCAST_ONESEG)		+= broadcast_dmb_drv_if.o
#obj-$(CONFIG_LGE_BROADCAST_ONESEG)		+= tcc3530/
obj-$(CONFIG_LGE_BROADCAST_ONESEG_TCC3530)		+= broadcast_dmb_drv_if.o
obj-$(CONFIG_LGE_BROADCAST_ONESEG_MB86A35S)		+= radio-mb86a35/
obj-$(CONFIG_LGE_BROADCAST_ONESEG_FC8150)		+= fc8150/
obj-$(CONFIG_LGE_BROADCAST_ONESEG_TCC3530)		+= tcc3530/

