# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_FSA8008)	+= hds_fsa8008.o
obj-$(CONFIG_SWITCH_MAX1462X)	+= hds_max1462x.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o

