obj-$(CONFIG_MACH_APQ8064_J1V) += board-j1.o \
	board-j1-camera.o \
	board-j1-display.o \
	board-j1-gpiomux.o \
	board-j1-gpu.o \
	board-j1-pmic.o \
	board-j1-regulator.o \
	board-j1-misc.o \
	board-j1-sound.o \
	board-j1-storage.o \
	board-j1-nfc.o

obj-$(CONFIG_MACH_APQ8064_J1U) += board-j1.o \
	board-j1-camera.o \
	board-j1-display.o \
	board-j1-gpiomux.o \
	board-j1-gpu.o \
	board-j1-pmic.o \
	board-j1-regulator.o \
	board-j1-misc.o \
	board-j1-sound.o \
	board-j1-storage.o \
	board-j1-nfc.o

obj-$(CONFIG_MACH_APQ8064_J1A) += board-j1.o \
	board-j1-camera.o \
	board-j1-display.o \
	board-j1-gpiomux.o \
	board-j1-gpu.o \
	board-j1-pmic.o \
	board-j1-regulator.o \
	board-j1-misc.o \
	board-j1-sound.o \
	board-j1-storage.o \
	board-j1-nfc.o

obj-$(CONFIG_MACH_APQ8064_J1SP) += board-j1.o \
	board-j1-camera.o \
	board-j1-display.o \
	board-j1-gpiomux.o \
	board-j1-gpu.o \
	board-j1-pmic.o \
	board-j1-regulator.o \
	board-j1-misc.o \
	board-j1-sound.o \
	board-j1-storage.o \
	board-j1-nfc.o

obj-$(CONFIG_MACH_APQ8064_J1D) += board-j1.o \
	board-j1-camera.o \
	board-j1-display.o \
	board-j1-gpiomux.o \
	board-j1-gpu.o \
	board-j1-pmic.o \
	board-j1-regulator.o \
	board-j1-misc.o \
	board-j1-sound.o \
	board-j1-storage.o \
	board-j1-nfc.o

obj-$(CONFIG_MACH_APQ8064_J1KD) += board-j1.o \
	board-j1-camera.o \
	board-j1-display.o \
	board-j1-gpiomux.o \
	board-j1-gpu.o \
	board-j1-pmic.o \
	board-j1-regulator.o \
	board-j1-misc.o \
	board-j1-sound.o \
	board-j1-storage.o \
	board-j1-nfc.o

obj-$(CONFIG_MACH_APQ8064_J1KT) += board-j1.o \
	board-j1-camera.o \
	board-j1-display.o \
	board-j1-gpiomux.o \
	board-j1-gpu.o \
	board-j1-pmic.o \
	board-j1-regulator.o \
	board-j1-misc.o \
	board-j1-sound.o \
	board-j1-storage.o \
	board-j1-nfc.o

obj-$(CONFIG_MACH_APQ8064_J1SK) += board-j1.o \
	board-j1-camera.o \
	board-j1-display.o \
	board-j1-gpiomux.o \
	board-j1-gpu.o \
	board-j1-pmic.o \
	board-j1-regulator.o \
	board-j1-misc.o \
	board-j1-sound.o \
	board-j1-storage.o \
	board-j1-nfc.o

obj-$(CONFIG_MACH_APQ8064_J1R) += board-j1.o \
	board-j1-camera.o \
	board-j1-display.o \
	board-j1-gpiomux.o \
	board-j1-gpu.o \
	board-j1-pmic.o \
	board-j1-regulator.o \
	board-j1-misc.o \
	board-j1-sound.o \
	board-j1-storage.o \
	board-j1-nfc.o

obj-$(CONFIG_MACH_APQ8064_J1B) += board-j1.o \
	board-j1-camera.o \
	board-j1-display.o \
	board-j1-gpiomux.o \
	board-j1-gpu.o \
	board-j1-pmic.o \
	board-j1-regulator.o \
	board-j1-misc.o \
	board-j1-sound.o \
	board-j1-storage.o \
	board-j1-nfc.o

obj-$(CONFIG_MACH_APQ8064_J1TL) += board-j1.o \
	board-j1-camera.o \
	board-j1-display.o \
	board-j1-gpiomux.o \
	board-j1-gpu.o \
	board-j1-pmic.o \
	board-j1-regulator.o \
	board-j1-misc.o \
	board-j1-sound.o \
	board-j1-storage.o \
	board-j1-nfc.o

obj-$(CONFIG_MACH_APQ8064_J1TM) += board-j1.o \
	board-j1-camera.o \
	board-j1-display.o \
	board-j1-gpiomux.o \
	board-j1-gpu.o \
	board-j1-pmic.o \
	board-j1-regulator.o \
	board-j1-misc.o \
	board-j1-sound.o \
	board-j1-storage.o \
	board-j1-nfc.o

obj-$(CONFIG_MACH_APQ8064_J1VD) += board-j1.o \
	board-j1-camera.o \
	board-j1-display.o \
	board-j1-gpiomux.o \
	board-j1-gpu.o \
	board-j1-pmic.o \
	board-j1-regulator.o \
	board-j1-misc.o \
	board-j1-sound.o \
	board-j1-storage.o \
	board-j1-nfc.o
	
obj-$(CONFIG_MACH_APQ8064_J1X) += board-j1.o \
	board-j1-camera.o \
	board-j1-display.o \
	board-j1-gpiomux.o \
	board-j1-gpu.o \
	board-j1-pmic.o \
	board-j1-regulator.o \
	board-j1-misc.o \
	board-j1-sound.o \
	board-j1-storage.o \
	board-j1-nfc.o
