obj-$(CONFIG_DIAG_CHAR) := diagchar.o
obj-$(CONFIG_DIAG_SDIO_PIPE) += diagfwd_sdio.o
obj-$(CONFIG_DIAG_BRIDGE_CODE) += diagfwd_hsic.o
obj-$(CONFIG_DIAG_BRIDGE_CODE) += diagfwd_smux.o
diagchar-objs := diagchar_core.o diagchar_hdlc.o diagfwd.o diagmem.o diagfwd_cntl.o diag_dci.o
obj-$(CONFIG_LGE_MTS) += mtsk_tty.o mtsk_bypass.o
obj-$(CONFIG_LGE_DM_APP) += lg_dm_tty.o
obj-$(CONFIG_LGE_USB_DIAG_DISABLE) += diag_lock.o
