obj-$(CONFIG_MACH_APQ8064_GKU) += board-gk.o \
	board-gk-camera.o \
	board-gk-display.o \
	board-gk-gpiomux.o \
	board-gk-gpu.o \
	board-gk-pmic.o \
	board-gk-regulator.o \
	board-gk-misc.o \
	board-gk-sound.o \
	board-gk-storage.o \
	board-gk-nfc.o \
	board-gk-rfkill.o

obj-$(CONFIG_MACH_APQ8064_GKSK) += board-gk.o \
	board-gk-camera.o \
	board-gk-display.o \
	board-gk-gpiomux.o \
	board-gk-gpu.o \
	board-gk-pmic.o \
	board-gk-regulator.o \
	board-gk-misc.o \
	board-gk-sound.o \
	board-gk-storage.o \
	board-gk-nfc.o \
	board-gk-rfkill.o

obj-$(CONFIG_MACH_APQ8064_GKKT) += board-gk.o \
	board-gk-camera.o \
	board-gk-display.o \
	board-gk-gpiomux.o \
	board-gk-gpu.o \
	board-gk-pmic.o \
	board-gk-regulator.o \
	board-gk-misc.o \
	board-gk-sound.o \
	board-gk-storage.o \
	board-gk-nfc.o \
	board-gk-rfkill.o

obj-$(CONFIG_MACH_APQ8064_GKATT) += board-gk.o \
	board-gk-camera.o \
	board-gk-display.o \
	board-gk-gpiomux.o \
	board-gk-gpu.o \
	board-gk-pmic.o \
	board-gk-regulator.o \
	board-gk-misc.o \
	board-gk-sound.o \
	board-gk-storage.o \
	board-gk-nfc.o \
	board-gk-rfkill.o 

obj-$(CONFIG_MACH_APQ8064_GKGLOBAL) += board-gk.o \
	board-gk-camera.o \
	board-gk-display.o \
	board-gk-gpiomux.o \
	board-gk-gpu.o \
	board-gk-pmic.o \
	board-gk-regulator.o \
	board-gk-misc.o \
	board-gk-sound.o \
	board-gk-storage.o \
	board-gk-nfc.o \
	board-gk-rfkill.o 
